### ISSUE TITLE
Error in Workflow 'OneNote Navigator'

### ISSUE THREAD

**Issue by Sodajunkie** [kevin-funderburg/alfred-microsoft-onenote-navigator#16]
![OneNote Navigator](https://user-images.githubusercontent.com/11729602/106903989-a6088280-66c8-11eb-91be-918c0a2ca732.png)

Here is the debug log:
[09:10:24.167] Logging Started...
[09:10:31.410] OneNote Navigator[Script Filter] Queuing argument '(null)'
[09:10:31.763] OneNote Navigator[Script Filter] Script with argv '(null)' finished
[09:10:31.766] ERROR: OneNote Navigator[Script Filter] Code 1: .
09:10:31 workflow.py:2061 DEBUG    ---------- OneNote Navigator (2.0.0) ----------
09:10:31 workflow.py:1468 DEBUG    reading settings from /Users/ms655/Library/Application Support/Alfred/Workflow Data/com.kfunderburg.oneNoteNav/settings.json
09:10:31 workflow.py:2343 DEBUG    update check not due
09:10:31 getNotebooks.py:302 DEBUG    Started workflow
09:10:31 getNotebooks.py:303 DEBUG    os.getenv('q'): 
09:10:31 getNotebooks.py:264 DEBUG    [u'-a']
09:10:31 workflow.py:1695 DEBUG    loading cached data: /Users/ms655/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.kfunderburg.oneNoteNav/__workflow_latest_version.cpickle
09:10:31 workflow.py:2080 ERROR    [Errno 2] No such file or directory: '/Users/ms655/Library/Containers/com.microsoft.onenote.mac/Data/Library/Application Support/Microsoft User Data/OneNote/15.0/FullTextSearchIndex/'
Traceback (most recent call last):
  File "/Users/ms655/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9A4DE82A-3642-44E1-8321-23CA14FF8687/workflow/workflow.py", line 2073, in run
    func(self)
  File "getNotebooks.py", line 313, in main
    path_map = wf.cached_data('path_map', update_path_map, max_age=300)
  File "/Users/ms655/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9A4DE82A-3642-44E1-8321-23CA14FF8687/workflow/workflow3.py", line 649, in cached_data
    return super(Workflow3, self).cached_data(name, data_func, max_age)
  File "/Users/ms655/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9A4DE82A-3642-44E1-8321-23CA14FF8687/workflow/workflow.py", line 1701, in cached_data
    data = data_func()
  File "getNotebooks.py", line 132, in update_path_map
    update_db()
  File "getNotebooks.py", line 125, in update_db
    def update_db(): create_db()
  File "getNotebooks.py", line 114, in create_db
    sql = queries.create_merged_db()
  File "/Users/ms655/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9A4DE82A-3642-44E1-8321-23CA14FF8687/queries.py", line 49, in create_merged_db
    for f in os.listdir(os.path.expanduser(ONENOTE_FULL_SEARCH_PATH)):
OSError: [Errno 2] No such file or directory: '/Users/ms655/Library/Containers/com.microsoft.onenote.mac/Data/Library/Application Support/Microsoft User Data/OneNote/15.0/FullTextSearchIndex/'
09:10:31 workflow.py:2082 INFO     for assistance, see: https://github.com/kevin-funderburg/alfred-microsoft-onenote-navigator
09:10:31 workflow.py:2103 DEBUG    ---------- finished in 0.061s ----------
[09:10:31.770] OneNote Navigator[Script Filter] {"items": [{"valid": false, "subtitle": "[Errno 2] No such file or directory: '/Users/ms655/Library/Containers/com.microsoft.onenote.mac/Data/Library/Application Support/Microsoft User Data/OneNote/15.0/FullTextSearchIndex/'", "icon": {"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"}, "title": "Error in workflow 'OneNote Navigator'"}]}
[09:10:32.284] OneNote Navigator[Script Filter] Queuing argument '(null)'
[09:10:32.497] OneNote Navigator[Script Filter] Script with argv '(null)' finished
[09:10:32.504] ERROR: OneNote Navigator[Script Filter] Code 1: .
09:10:32 workflow.py:2061 DEBUG    ---------- OneNote Navigator (2.0.0) ----------
09:10:32 workflow.py:1468 DEBUG    reading settings from /Users/ms655/Library/Application Support/Alfred/Workflow Data/com.kfunderburg.oneNoteNav/settings.json
09:10:32 workflow.py:2343 DEBUG    update check not due
09:10:32 getNotebooks.py:302 DEBUG    Started workflow
09:10:32 getNotebooks.py:303 DEBUG    os.getenv('q'): 
09:10:32 getNotebooks.py:264 DEBUG    [u'-a']
09:10:32 workflow.py:1695 DEBUG    loading cached data: /Users/ms655/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.kfunderburg.oneNoteNav/__workflow_latest_version.cpickle
09:10:32 workflow.py:2080 ERROR    [Errno 2] No such file or directory: '/Users/ms655/Library/Containers/com.microsoft.onenote.mac/Data/Library/Application Support/Microsoft User Data/OneNote/15.0/FullTextSearchIndex/'
Traceback (most recent call last):
  File "/Users/ms655/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9A4DE82A-3642-44E1-8321-23CA14FF8687/workflow/workflow.py", line 2073, in run
    func(self)
  File "getNotebooks.py", line 313, in main
    path_map = wf.cached_data('path_map', update_path_map, max_age=300)
  File "/Users/ms655/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9A4DE82A-3642-44E1-8321-23CA14FF8687/workflow/workflow3.py", line 649, in cached_data
    return super(Workflow3, self).cached_data(name, data_func, max_age)
  File "/Users/ms655/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9A4DE82A-3642-44E1-8321-23CA14FF8687/workflow/workflow.py", line 1701, in cached_data
    data = data_func()
  File "getNotebooks.py", line 132, in update_path_map
    update_db()
  File "getNotebooks.py", line 125, in update_db
    def update_db(): create_db()
  File "getNotebooks.py", line 114, in create_db
    sql = queries.create_merged_db()
  File "/Users/ms655/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9A4DE82A-3642-44E1-8321-23CA14FF8687/queries.py", line 49, in create_merged_db
    for f in os.listdir(os.path.expanduser(ONENOTE_FULL_SEARCH_PATH)):
OSError: [Errno 2] No such file or directory: '/Users/ms655/Library/Containers/com.microsoft.onenote.mac/Data/Library/Application Support/Microsoft User Data/OneNote/15.0/FullTextSearchIndex/'
09:10:32 workflow.py:2082 INFO     for assistance, see: https://github.com/kevin-funderburg/alfred-microsoft-onenote-navigator
09:10:32 workflow.py:2103 DEBUG    ---------- finished in 0.052s ----------
[09:10:32.509] OneNote Navigator[Script Filter] {"items": [{"valid": false, "subtitle": "[Errno 2] No such file or directory: '/Users/ms655/Library/Containers/com.microsoft.onenote.mac/Data/Library/Application Support/Microsoft User Data/OneNote/15.0/FullTextSearchIndex/'", "icon": {"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"}, "title": "Error in workflow 'OneNote Navigator'"}]}

**Comment by homerjay88xx** [comment]
+1
